version: '3'
services:

  postgres:
    image: postgres
    networks:
      - mynet
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
      - APP_DB_NAME=backendtest
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  config-service:
    image: config-service
    networks:
      - mynet

  registry-service:
    image: registry-service
    networks:
      - mynet
    depends_on:
      - config-service
    command: sh -c "/wait && java -jar registry-service.jar"
    environment:
      - WAIT_HOSTS=config-service:8081
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=20
      - WAIT_HOST_CONNECT_TIMEOUT=30

  imagen-service:
    image: imagen-service
    networks:
      - mynet
    depends_on:
      - registry-service

  usuario-service:
    image: usuario-service
    networks:
      - mynet
    depends_on:
      - registry-service
      - postgres

  gateway-service:
    image: gateway-service
    networks:
      - mynet
    ports:
      - 8080:8080
    depends_on:
      - registry-service

networks:
  mynet: