version: '3'
services:
  config-service:
    image: config-service
    networks:
      - mynet

  registry-service:
    image: registry-service
    networks:
      - mynet

  gateway-service:
    image: gateway-service
    networks:
      - mynet
    ports:
      - 8080:8080

  usuario-service:
    image: usuario-service
    networks:
      - mynet
    ports:
      - 8091:8091

  imagen-service:
    image: imagen-service
    networks:
      - mynet
    ports:
      - 8092:8092

  postgres:
    image: postgres
    networks:
      - mynet
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
      - APP_DB_NAME=crecimiento
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

networks:
  mynet: